[[mgr.prepend_keymap]]
on = "y" 
run = [
  '''
  shell 'xclip -selection clipboard -t image/png -i "$@"' --confirm
  ''',
  "yank"
] 
desc = "Yank image and copy it to clipboard" 

[[mgr.prepend_keymap]]
on   = "<C-s>"
run  = 'shell "$SHELL" --block --confirm' 
desc = "Open shell here" 

[[mgr.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd ~/Downloads"
desc = "Cd to ~/Downloads"

[[mgr.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/Pictures/"
desc = "Cd to ~/Pictures"

[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd ~/SparkFun/"
desc = "Cd to ~/SparkFun"

[[mgr.prepend_keymap]]
on   = [ "g", "g" ]
run  = "cd ~/Git-Personal/"
desc = "Cd to ~/Git-Personal/"
