[opener]
app_image = [
{ run = '"$0"', orphan = true, desc = "Run AppImage", for = "unix" }
]
pdf = [
{ run = 'xreader "$0"', orphan = true, desc = "Open PDF", for = "unix" }
]

[open]
prepend_rules = [
{name = "*.AppImage", use = ["app_image"]},
{name = "*.pdf", use = ["pdf"]},
]

[manager]
ratio = [2,3,3]
