window.startup_mode = "Maximized"
window.blur = true
font.normal={family="FiraCode Nerd Font",style="Regular"}
font.bold={family="FiraCode Nerd Font",style="Bold"}
font.italic={family="FiraCode Nerd Font",style="Italic"}
font.bold_italic={family="FiraCode Nerd Font",style="Bold Italic"}
cursor.style={shape="Underline",blinking="On"}
cursor.vi_mode_style={shape="Underline",blinking="On"}
window.opacity=0.8
font.size=12
import=[
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
[env]
  TERM="xterm-256color"

