import= [
    "~/.config/alacritty/themes/themes/github_dark.toml"
]

[font]
  normal={family="SpaceMono Nerd Font",style="Regular"}
  bold={family="SpaceMono Nerd Font",style="Bold"}
  italic={family="SpaceMono Nerd Font",style="Italic"}
  bold_italic={family="SpaceMono Nerd Font",style="Bold Italic"}
  size=12.5

[cursor]
  style={shape="Underline",blinking="On"}
  vi_mode_style={shape="Underline",blinking="On"}

[window]
  opacity=0.8
  blur=true
  startup_mode="Maximized"

[env]
  TERM="xterm-256color"

